bussels_app/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from django.views.generic import TemplateView
from views import *

urlpatterns = [
    url(r'^all/$', BusselListView.as_view(), name="all-bussels"),
    url(r'^authenticate/$', authenticate_bussel_request, name="bussel-authenticate"),
    url(r'^change/password/$', change_bussel_password, name="bussel-password-change"),
    url(r'^update/location/$', update_bussel_location, name="bussel-update-location"),
    url(r'^reports/all$', BusselReportListView.as_view(), name="all-bussel-reports"),
    url(r'^performance$', BussellPerformanceMetricsView.as_view(), name="bussel-performance"),
    url(r'^performance/json/$', get_performance_data, name="bussell-performance-json"),
    url(r'^performance/monthly_average/json/$', get_monthly_average, name="bussell-performance-monthly-json"),
    url(r'^reports/all/export$', export_bussels_list, name="all-bussel-export"),
    url(r'^reports/month/export$', export_bussel_monthly_reports, name="monthly-bussel-export"),
    url(r'^reports/headers/all/json/$', bussell_reports_header_json, name="all-bussel-header-list"),
    url(r'^reports/details/(?P<pk>\d+)/$', BusselReportEditView.as_view(), name="bussel-report-detail"),
    url(r'^all/json/$', json_bussel_list, name="all-bussels-json"),
    url(r'^reports/all/json$', json_bussel_reports_list, name="all-bussel-reports-json"),
    url(r'^reports_for_bussel/all/$', get_reports_for_bussel, name="reports-for-bussel"),
    url(r'^bussel_reports/all/export$', export_bussel_reports, name="bussel-reports-export"),
    url(r'^details/(?P<pk>\d+)/$', BusselDetailView.as_view(), name="bussel-detail"),
    url(r'^report/save/$', save_bussel_report, name="bussel-report-save"),
    url(r'^report/check/$', check_attendance_status, name="bussel-report-check"),
    url(r'^member/save/$', save_bussell_member, name="bussel-member-save"),
    url(r'^members/get/all/$', get_all_bussell_members, name="bussel-members-all"),
    url(r'^report/attendance/all/$', get_members_attendance_for_report, name="bussell-report-attendance"),
    url(r'^report/attendance/update/$', update_church_attendance),
    url(r'^profile/save/$', update_bussell_profile, name="bussel-profile-save"),
    url(r'^profile/get/$', get_bussell_group_pic_url, name="bussel-profile-get"),
]

lcidarkuman/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import bussels_app
import info_system

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    # Examples:
    # url(r'^$', 'lcidarkuman.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^bussels/', include('bussels_app.urls', namespace="bussel")),
    url(r'^info/', include('info_system.urls', namespace="info")),
    url(r'^pastoral/', include('pastoral_care.urls', namespace="pastoral")),
    url(r'^notice/', include('notice_board.urls', namespace="noticeboard")),
    url(r'^finance/', include('treasury.urls', namespace="finance")),
    url(r'^events/', include('events_calendar.urls', namespace="events")),
    url(r'^json/', include('bussels_app.urls', namespace="ajax")),
    url(r'^under_development/', bussels_app.views.SectionUnderDevelopment.as_view(), name="under-dev"),
    url(r'^$', bussels_app.views.SectionUnderDevelopment.as_view(), name="under-dev"),
    url(r'^access_denied/', bussels_app.views.AccessDenied.as_view(), name="access-denied"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('django.contrib.auth.urls')),
]

treasury/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from django.views.generic import TemplateView
from views import *

urlpatterns = [
    url(r'^offering/all/$', get_all_offerings, name="offering-all"),
    url(r'^tithe/all/$', get_all_tithes, name="tithe-all"),
    url(r'^tithe/add/$', add_tithe, name="tithe-add"),
    url(r'^offering/add/$', add_offering, name="offering-add"),
]

bussels_app/models.py
from django.db import models
from djgeojson.fields import PointField
from info_system.models import Member
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.contrib.auth.hashers import *
from django.utils.crypto import get_random_string

from django.db.models import Func, F, Sum

DAYS = [
    (0, "Sunday"),
    (1, "Monday"),
    (2, "Tuesday"),
    (3, "Wednesday"),
    (4, "Thursday"),
    (5, "Friday"),
    (6, "Saturday"),
]

STATUS = [
    (0, "Inactive"),
    (1, "Active"),
]

GENDER = [
    (0, "Male"),
    (1, "Female"),
]

class Bussel(models.Model):
    # Bussel Information ---------------------
    name            = models.CharField(max_length=50)
    code            = models.CharField(max_length=10)
    zone            = models.CharField(max_length=5)
    meeting_day     = models.IntegerField(choices=DAYS)
    meeting_time    = models.TimeField()
    password        = models.CharField(max_length=100) 

    # Bussel Location ------------------------
    house_number    = models.CharField(max_length=50)
    street_name     = models.CharField(max_length=50)
    suburb          = models.CharField(max_length=50)
    bussel_location = PointField(null=True)

    # Bussel Leader --------------------------
    leader = models.ForeignKey(Member)

    # Meta Data ------------------------------
    status       = models.IntegerField(choices=STATUS, default=0)
    date_created = models.DateField(auto_now_add=True)

    group_pic = models.URLField(null=True, blank=True, max_length=400)

    def __unicode__(self):
        return self.name + " (" + self.leader.first_name + " " + self.leader.last_name + ")"


# Weekly Report ------------------------------
class BusselReport(models.Model):
    bussel             = models.ForeignKey(Bussel)
    topic              = models.CharField(max_length=100)
    notes              = models.CharField(max_length=512, null=True)
    date               = models.DateField()
    time               = models.TimeField(auto_now_add=True)
    time_started       = models.TimeField()
    time_ended         = models.TimeField()
    bussel_attendance  = models.IntegerField()
    church_attendance  = models.IntegerField(default=0)
    num_souls_won      = models.IntegerField()
    num_first_timers   = models.IntegerField()
    offertory_given    = models.FloatField()

    class Meta:
        get_latest_by = 'date'

    def __unicode__(self):
        return self.bussel.name + "--" + self.topic

class Month(Func):
    function = 'EXTRACT'
    template = '%(function)s(MONTH from %(expressions)s)'
    output_field = models.IntegerField()

class BussellMember(models.Model):
    first_name = models.CharField(max_length=100)
    other_names = models.CharField(max_length=100)
    phone = models.CharField(max_length=15, null=True)
    address = models.CharField(max_length=100, null=True)
    date_of_birth = models.DateField()
    date_joined = models.DateField()
    gender = models.IntegerField(choices=GENDER, default=0)
    church_member = models.BooleanField(default=False)
    profile_pic = models.URLField(null=True, max_length=400)
    bussell = models.ForeignKey(Bussel)
    
    def __unicode__(self):
        return self.bussell.name + " -> " +self.first_name+ " "+self.other_names

class BussellMemberAttendance(models.Model):
    bussell_member = models.ForeignKey(BussellMember)
    bussell_report = models.ForeignKey(BusselReport)
    bussell_attendance = models.BooleanField(default=False)
    church_attendance = models.BooleanField(default=False)

    def __unicode__(self):
        return self.bussell_member.first_name + " " + str(self.bussell_attendance)

# Generate unique xxxx-xxxx hex code for each bussel
def get_hex_code():
    allowed_chars = 'ABCDEF0123456789'
    code = get_random_string(length=4, allowed_chars=allowed_chars) + \
        "-" + get_random_string(length=4, allowed_chars=allowed_chars)
    return code


# Signals --------------------------------------

# hash raw password from form
@receiver(pre_save, sender=Bussel)
def hash_password(sender, **kwargs):
    raw_password = kwargs['instance'].password
    if is_password_usable(raw_password):
        return
    else:
        hashed_password = make_password(raw_password)
        kwargs['instance'].password = hashed_password
    return


# get a unique hex code 
@receiver(pre_save, sender=Bussel)
def save_hex_code(sender, **kwargs):
    bussel = kwargs['instance']
    if bussel.pk is not None:
        print "already has code"
        return
    code = get_hex_code()
    existing_codes = Bussel.objects.all().values_list('code')
    while code in existing_codes:
        code = get_hex_code()
    bussel.code = code
    print code
    return

bussels_app/forms.py
from django import forms
from models import Bussel

class BusselReportDetailForm(forms.Form):
    topic = forms.CharField(label="Topic:", max_length=200)
    date  = forms.DateField(widget=forms.TextInput(attrs={'disabled': True}),\
                            label="Report Date:", required=False)
    time  = forms.TimeField(widget=forms.TextInput(attrs={'disabled': True}),\
                            label="Report Time:", required=False)
    time_started    = forms.TimeField(label="Bussel Start Time:")
    time_ended      = forms.TimeField(label="Bussel End Time:")
    bussel_attendance = forms.IntegerField(label="Bussel Attendance:")
    church_attendance = forms.IntegerField(label="Church Attendance:", min_value=0)
    num_souls_won     = forms.IntegerField(label="Souls Won:")
    num_first_timers  = forms.IntegerField(label="First Timers:")
    offertory_given   = forms.DecimalField(label="Offertory(GHS):", decimal_places=2, max_digits=10)


class BussellPerformanceMetricsForm(forms.Form):
    bussell = forms.ModelChoiceField(Bussel.objects.filter(status=1))
    from_date = forms.DateField(input_formats=('%d-%m-%Y',))
    to_date = forms.DateField(input_formats=('%d-%m-%Y',))

templates/bussels_app/access_denied.html
{% extends "base.html" %}

{% block contents %}
<div class="main-contents">
    <div class="section-header">
	    <p class=section-title>Access Denied</p>
    </div>
    <div class="data-container" id=>
	    <div class="access_denied_div">
		    <img src="/static/access_denied.png" alt="not found" height:"256" width:"300" id="access_denied_img">
		   <h2 id="access_denied_string">You do not have permission to access this content!</h2>
	    </div>

    </div>
</div>
{% endblock %}

{% block footer %}
{% include "footer.html" %}
{% endblock %}

templates/bussels_app/bussel_list.html
{% extends "base.html" %}

{% block contents %}
<div class="main-contents">
    <div class="section-header">
	    <p class=section-title>All Bussels <span class="badge bussel-count">0</span></p>
	    <input class=search-box type="text" name="search" placeholder="Search...">
	    <input class=search-btn type="button" name="search-btn" value=Search>
	    <div class="section-item">
	         <a href="#">
		     <span class="fa fa-sort"></span>
		     Sort
		 </a>
	    </div>
	    <div class="section-item dropdown">
	         <a href="#" data-toggle="dropdown" class="dropdown-toggle">
		     <span class="fa fa-upload"></span>
		     Export
		 </a>
		 <ul class="dropdown-menu">
			 <li><a href=""><span class="fa fa-file-excel-o"></span> Microsoft Excel</a></li>
			 <li><a href="{% url 'bussel:all-bussel-export'%}?export_type=pdf"><span class="fa fa-file-pdf-o"></span> PDF Document</a></li>
		 </ul>
	    </div>
    </div>
    <div class="data-container" id=bussel_list>
	    <div class="empty_error_div">
		    <img src="/static/404_error_image.png" alt="not found" height:"205" width:"300" id="r404_image">
		   <h2 id="empty_error_string">Oops! Your request returned no data.</h2>
	    </div>

	    <table class="table table-striped table-hover" 
		    id=bussel_table
		    data-toggle="table"
		    data-search="true"
		    data-show-columns="true">
                <thead>
	         <th data-sortable="true">Bussel Name</th>
	         <th>Bussel Code</th>
	         <th data-sortable="true">Bussel Leader</th>
	         <th>Bussel Location</th>
		</thead>	    
		<tbody>
	        	
		</tbody>
	    </table>
    </div>
</div>
{% endblock %}
{% block footer %}
{% include "footer.html" %}
	<script>
$(document).ready(function(){
	$(".empty_error_div").hide();
	$("#bussel-all-link").addClass("active");
	$("#bussells_link").addClass("active");
        $.ajax({
            type: 'GET',
            url: "{% url 'ajax:all-bussels-json' %}",
	    data: {get_param: 'value'},
	    dataType: 'json',
	    success: function(data) {
		    $.each(data, function(i, bussel) {
			    var detail_link = "/bussels/details/"+bussel.pk + "/"
			    $(".table > tbody").append('<tr> \
			          <td><a href="" class=' + bussel.pk + '>' + bussel.name + '</a></td> \
			          <td><a href="" class=' + bussel.pk + '>' + bussel.code + '</a></td> \
				  <td><a href="" class=' + bussel.pk + '>' + bussel.leader + '</a></td> \
			          <td><a href="" class=' + bussel.pk + '>' + bussel.location + '</a></td></tr>'
				  );
		            $("."+bussel.pk).attr('href', detail_link);
                    $(".badge.bussel-count").html(data.length);
		    })
	    }
        })
	$(".search-box").keyup(function () {
	    var searchTerm = $(".search-box").val();
	    var listItem = $('.table tbody').children('tr');
	    var searchSplit = searchTerm.replace(/ /g, "'):containsi('")
		        
		      $.extend($.expr[':'], {'containsi': function(elem, i, match, array){
		              return (elem.textContent || elem.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
		          }
		        });
	        
	      $(".table tbody tr").not(":containsi('" + searchSplit + "')").each(function(e){
	          $(this).hide();
		  if($('.table tbody tr').find(':visible').length===0){
			  $('.table').hide();
			  $('.empty_error_div').show();
		  }
	        });
	      
	        $(".table tbody tr:containsi('" + searchSplit + "')").each(function(e){
		    $('.empty_error_div').hide();
                    $('.table').show();
		    $(this).show();
		  })
        })
})
	</script>
{% endblock %}

templates/bussels_app/bussel_report_detail.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block contents %}
<div class="main-contents">
    <div class="section-header">
	    <p class=section-title>{{bussel_name}}</p>
    </div>
    <div class="data-container" id=bussel_report_details>
	    <div class="data-section">
	           <div class="data-section-header">
			   <p class="subsection-title">Bussell Report Detail</p>
		   </div>
		   <div class="data-section-data">
			   <form action="#" role="form" method="post">
			      {% csrf_token %} 
			      <div class="row">
				      <div class="form-group col-sm-6">
					 <label class="control-label" for="{{form.topic.auto_id}}">
					 {{form.topic.label}} 
					 </label>
					 {% render_field form.topic class+="form-control" %}
				      </div>
				      <div class="form-group col-sm-3">
					 <label class="control-label" for="{{form.bussel_attendance.auto_id}}">
					 {{form.bussel_attendance.label}} 
					 </label>
					 {% render_field form.bussel_attendance class+="form-control" %}
				      </div>
				      <div class="form-group col-sm-3">
					 <label class="control-label" for="{{form.church_attendance.auto_id}}">
					 {{form.church_attendance.label}} 
					 </label>
					 {% render_field form.church_attendance class+="form-control" %}
				      </div>
			      </div>
			      <div class="row">
				      <div class="form-group col-sm-6">
					 <label class="control-label" for="{{form.time_started.auto_id}}">
					 {{form.time_started.label}} 
					 </label>
					 {% render_field form.time_started class+="form-control" %}
				      </div>
				      <div class="form-group col-sm-6">
					 <label class="control-label" for="{{form.time_ended.auto_id}}">
					 {{form.time_ended.label}} 
					 </label>
					 {% render_field form.time_ended class+="form-control" %}
				      </div>
			      </div>
			      <div class="row">
				      <div class="form-group col-sm-4">
					 <label class="control-label" for="{{form.num_first_timers.auto_id}}">
					 {{form.num_first_timers.label}} 
					 </label>
					 {% render_field form.num_first_timers class+="form-control" %}
				      </div>
				      <div class="form-group col-sm-4">
					 <label class="control-label" for="{{form.num_souls_won.auto_id}}">
					 {{form.num_souls_won.label}} 
					 </label>
					 {% render_field form.num_souls_won class+="form-control" %}
				      </div>
				      <div class="form-group col-sm-4">
					 <label class="control-label" for="{{form.offertory_given.auto_id}}">
					 {{form.offertory_given.label}} 
					 </label>
					 {% render_field form.offertory_given class+="form-control" %}
				      </div>
			      </div>
			      <div class="row">
				      <div class="form-group col-sm-6">
					 <label class="control-label" for="{{form.date.auto_id}}">
					 {{form.date.label}} 
					 </label>
					 {% render_field form.date class+="form-control" %}
				      </div>
				      <div class="form-group col-sm-6">
					 <label class="control-label" for="{{form.time.auto_id}}">
					 {{form.time.label}} 
					 </label>
					 {% render_field form.time class+="form-control" %}
				      </div>
			      </div>

			      <div>
			          <button type=submit class="btn btn-primary" id="bussel_save_btn">
					  Save Changes 
				  </button>
			      </div>
			   </form>
		     </div>
		 </div>
    </div>
</div>
{% endblock %}

{% block footer %}
{% include "footer.html" %}

<script>
$(document).ready(function(){
    $("#bussel-report-link").addClass("active");
})
</script>
{% endblock %}

templates/bussels_app/bussel_reports_list.html
{% extends "base.html" %}

{% block contents %}
<div class="main-contents">
    <div class="section-header">
	    <p class=section-title>Bussell Reports <span class="badge bussel-count">0</span></p>

	    <input class=search-box id=report-search type="text" name="search" placeholder="Search...">
	    <input class=search-btn type="button" name="search-btn" value=Search>
	    <div class="section-item">
	         <a href="#">
		     <span class="fa fa-sort"></span>
		     Sort
		 </a>
	    </div>

	    <div class="section-item dropdown">
	         <a href="#" data-toggle="dropdown" class="dropdown-toggle">
		     <span class="fa fa-upload"></span>
		     Export
		 </a>
		 <ul class="dropdown-menu">
			 <li><a href=""><span class="fa fa-file-excel-o"></span> Microsoft Excel</a></li>
			 <li><a href="{% url 'bussel:bussel-reports-export'%}?export_type=pdf"><span class="fa fa-file-pdf-o"></span> PDF Document</a></li>
		 </ul>
	    </div>
	    <div class="section-item">
		    <select class="form-control" id=saturday-combo onchange=get_bussel_reports(this.value)>
			    {% for saturday in saturdays%}
			    <option value={{saturday|date:"Y-m-d"}}> {{saturday}} </option>
			    {%endfor%}
		    </select>
	    </div>
    </div>
    <div class="data-container" id=bussel_report_list>
	    <table class="table table-striped table-hover" 
		    id=bussel_report_table
		    data-toggle="table"
		    data-search="true">
                <thead>
	         <th>Bussell Name</th>
	         <th>Bussell Leader</th>
	         <th>Topic</th>
	         <th>Attendance</th>
	         <th>Report Time</th>
		</thead>	    
		<tbody>
	        	
		</tbody>
	    </table>

	    <div class="empty_error_div">
		    <img src="/static/404_error_image.png" alt="not found" height:"205" width:"300" id="r404_image">
		   <h2 id="empty_error_string">Oops! Your request returned no data.</h2>
	    </div>

	    <div class="data-section">
	           <div class="data-section-header" id="week-summary-header">
			   <p class="subsection-title">Week's Summary</p>
		   </div>
		   <div class="data-section-data">
			   <div class="row">
			       <div class="col-sm-3">
				       <p>Reports Received: <b id=report-total></b></p>
			       </div>
			       <div class="col-sm-3">
				       <p>Total Attendance: <b id=attendance-total>{{object.code}}</b></p>
			       </div>
			       <div class="col-sm-3">
				       <p>Total Offertory(GHS): <b id=offertory-total>{{object.zone}}</b></p>
			       </div>
			       <div class="col-sm-3">
				       <p>Total Souls Won: <b id=souls-total>{{object.zone}}</b></p>
			       </div>
			   </div>
	          </div>
	    </div>
    </div>
</div>
{% endblock %}
{% block footer %}
{% include "footer.html" %}
	<script>
$(document).ready(function(){
	$(".empty_error_div").hide();
	$("#bussel-report-link").addClass("active");
	$("#bussells_link").addClass("active");
	get_bussel_reports(document.getElementById("saturday-combo").value);
        
	//filter function
	$(".search-box").keyup(function () {
	    var searchTerm = $(".search-box").val();
	    var listItem = $('.table tbody').children('tr');
	    var searchSplit = searchTerm.replace(/ /g, "'):containsi('");
		        
		      $.extend($.expr[':'], {'containsi': function(elem, i, match, array){
		              return (elem.textContent || elem.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
		          }
		        });
	        
	      $(".table tbody tr").not(":containsi('" + searchSplit + "')").each(function(e){
	          $(this).attr('visible','false');
	        });
	      
	        $(".table tbody tr:containsi('" + searchSplit + "')").each(function(e){
		    $(this).attr('visible','true');
		    $(this).hightlight(searchSplit);
		  })
        })
})

function get_bussel_reports(report_date) {
        $.ajax({
            type: 'GET',
            url: "{% url 'ajax:all-bussel-reports-json' %}",
	    data: {request_date: report_date},
	    dataType: 'json',
	    success: function(data) {
	            $(".table tbody tr").remove();
		    $(".table").hide();
		    $(".data-section").hide();
		    $(".badge.bussel-count").html(data.length);
		    console.log(data)
		    if(data.length == 0) {
			    console.log(data.length);
			 $(".empty_error_div").show();
			 return;
		    }
		    else {
			    $("#report-total").html(data.length);
			    $("#offertory-total").html((data[0].offertory_given__sum).toFixed(2));
			    $("#souls-total").html(data[0].num_souls_won__sum);
			    $("#attendance-total").html(data[0].church_attendance__sum + '/' + data[0].bussel_attendance__sum);
			    $(".empty_error_div").hide();
		            $(".table").show();
		            $(".data-section").show();
			    $.each(data, function(i, bussel) {
				    var detail_link = "/bussels/reports/details/"+bussel.pk + "/"
				    $(".table > tbody").append('<tr> \
					  <td><a href="" class=' + bussel.pk + '>' + bussel.name + '</a></td> \
					  <td><a href="" class=' + bussel.pk + '>' + bussel.leader + '</a></td> \
					  <td><a href="" class=' + bussel.pk + '>' + bussel.topic + '</a></td> \
		   <td><a href="" class=' + bussel.pk + '>' + bussel.c_attendance+' / '+ bussel.b_attendance + '</a></td> \
					  <td><a href="" class=' + bussel.pk + '>' + bussel.time + '</a></td></tr>'
					  );
				    $("."+bussel.pk).attr('href', detail_link);
			    })
	            }
	    }
        })
}
	</script>
{% endblock %}

templates/bussels_app/bussell_performance_metrics.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block contents %}
<div class="main-contents">
    <div class="section-header">
	    <p class=section-title>Bussell Performance Metrics</p>
    </div>
    <div class="data-container">
	    <div class="data-section">
		    <div class="data-section-data">
			    <div class="form-group col-md-4">
				    <label class="control-label" for="id_bussell">Select Bussell:</label>
				   {% render_field form.bussell class+="form-control" %} 
			    </div>
			    <div class="col-md-4"></div>
			    <div class="form-group col-md-2">
				    <label class="control-label" for="id_from_date">Start Date:</label>
				   {% render_field form.from_date class+="form-control from_datepicker" %} 
			    </div>
			    <div class="form-group col-md-2">
				    <label class="control-label" for="id_to_date">End Date:</label>
				   {% render_field form.to_date class+="form-control to_datepicker" %} 
			    </div>
		    </div>

		    <div id="chart-container" style="position: relative, height:80vh, width=100vw, margin: 20px">
			      <canvas id="chart"></canvas>
		    </div>
	    </div>
    </div>
</div>
{% endblock %}

{% block footer %}
{% include "footer.html" %}

<script>
$(document).ready(function(){
	$("#bussells_link").addClass("active");
	chart_data = [];
	var attendanceBarChart = null;

	var attendanceTable = $("#monthly-average-table").DataTable({
                               "paging": false,
			       "ordering": false,
			       "info": false
	});

		$(".from_datepicker").datepicker({
	            changeMonth: true,
	            changeYear: false,
		    dateFormat: "yy-mm-dd",
		    defaultDate: "17-01-01",
		    maxDate:'0',
		});

		$(".to_datepicker").datepicker({
	            changeMonth: true,
	            changeYear: false,
		    dateFormat: "yy-mm-dd",
		    defaultDate: new Date(),
		    maxDate:'0',
		});

		$("#id_bussell, #id_from_date, #id_to_date").on('change', function(e) {
			var bussell_id = $("#id_bussell").val();
			var from_date =$.datepicker.formatDate('yy-mm-dd', 
					$("#id_from_date").datepicker("getDate"));
			var to_date = $.datepicker.formatDate('yy-mm-dd', 
					$("#id_to_date").datepicker("getDate"));
			if(from_date == "" || to_date == "") {
				return;
			
			}
			console.log(typeof(from_date))
			console.log(to_date)
			$.ajax({
			    type: 'GET',
			    url: "{% url 'bussel:bussell-performance-json' %}",
			    data: {pk: bussell_id, from: from_date, to:to_date},
			    dataType: 'json',
			    success: function(data) {
				    $('#chart').remove();
				    $('#chart-container').append('<canvas id="chart"></canvas>')
				    chart_data = data;
				    drawChart();
				    },

			    beforeSend: function(){
			            $('#chart-container').LoadingOverlay("show");
			    },

			    complete: function(){
			            $('#chart-container').LoadingOverlay("hide");
			    }
		        });
		});
})
function drawChart() {
	var ctx = document.getElementById("chart").getContext("2d");
	var data = {
		labels : chart_data[0],
		datasets: [
	        {
			label: "bussel attendance",
		        borderColor: "#bce0ba",
			backgroundColor: "#bce0ba",
			data: chart_data[1] 
		},	
	        {
			label: "church attendance",
		        borderColor: "#e6b795",
			backgroundColor: "#e6b795",
			data:  chart_data[2]
		},	
		]
	}
	var attendanceBarChart = new Chart(ctx, {
            type: 'bar',
            data: data,
            options: {
	            scales: {
			  yAxes: [{
			      ticks: {
				 max: 30,
				 min: 0,
				 stepSize: 1
			      },
			      scaleLabel: {
				 display: true,
				 labelString: 'Attendance'
			      }
			  }]
		    }
	    }	    
	});
     
}
</script>
{% endblock %}

templates/bussels_app/under_development.html
{% extends "base.html" %}

{% block contents %}
<div class="main-contents">
    <div class="section-header">
	    <p class=section-title>Section Under Development</p>
    </div>
    <div class="data-container" id=>
	    <div class="under_development_div">
		    <img src="/static/under_development.png" alt="not found" height:"245" width:"300" id="under_dev_img">
		   <h2 id="under_development_string">This section is under development!</h2>
	    </div>

    </div>
</div>
{% endblock %}

{% block footer %}
{% include "footer.html" %}
{% endblock %}