lcidarkuman/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import bussels_app
import info_system

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    # Examples:
    # url(r'^$', 'lcidarkuman.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^bussels/', include('bussels_app.urls', namespace="bussel")),
    url(r'^info/', include('info_system.urls', namespace="info")),
    url(r'^pastoral/', include('pastoral_care.urls', namespace="pastoral")),
    url(r'^notice/', include('notice_board.urls', namespace="noticeboard")),
    url(r'^finance/', include('treasury.urls', namespace="finance")),
    url(r'^events/', include('events_calendar.urls', namespace="events")),
    url(r'^json/', include('bussels_app.urls', namespace="ajax")),
    url(r'^under_development/', bussels_app.views.SectionUnderDevelopment.as_view(), name="under-dev"),
    url(r'^$', bussels_app.views.SectionUnderDevelopment.as_view(), name="under-dev"),
    url(r'^access_denied/', bussels_app.views.AccessDenied.as_view(), name="access-denied"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('django.contrib.auth.urls')),
]

pastoral_care/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from views import *
from forms import *

urlpatterns = [
    url('^members/all/$', MemberShipListView.as_view(), name="all-members"),
    url('^members/details/(?P<pk>\d+)/$', MemberDetailView.as_view()),
    url('^members/edit/(?P<pk>\d+)/$', MemberEditView.as_view()),
    url('^members/all/json/$', json_member_list, name="all-members-json"),
    url('^members/new/$', AddNewMemberView.as_view(form_class=NewMemberForm), name="new-member"),
    url('^members/export$', export_members, name="export-members"),
    url('^attendance/authorize/$', authorize_attendance, name="authorize-attendance"),
    url('^attendance/start/$', start_attendance, name="start-attendance"),
    url('^attendance/finish/$', finish_attendance, name="finish-attendance"),
    url('^attendance/all/json/$', json_attendance_list, name="all-attendance-json"),
    url('^attendance/assigned/json/$', get_assigned_members, name="assigned-attendance-json"),
    url('^attendance/insession/details/$', get_attendance_insession_details, name="insession-details"),
    url('^attendance/submit/$', submit_attendance, name="attendance-submit"),
]

treasury/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from django.views.generic import TemplateView
from views import *

urlpatterns = [
    url(r'^offering/all/$', get_all_offerings, name="offering-all"),
    url(r'^tithe/all/$', get_all_tithes, name="tithe-all"),
    url(r'^tithe/add/$', add_tithe, name="tithe-add"),
    url(r'^offering/add/$', add_offering, name="offering-add"),
]

bussels_app/models.py
from django.db import models
from djgeojson.fields import PointField
from info_system.models import Member
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.contrib.auth.hashers import *
from django.utils.crypto import get_random_string

from django.db.models import Func, F, Sum

DAYS = [
    (0, "Sunday"),
    (1, "Monday"),
    (2, "Tuesday"),
    (3, "Wednesday"),
    (4, "Thursday"),
    (5, "Friday"),
    (6, "Saturday"),
]

STATUS = [
    (0, "Inactive"),
    (1, "Active"),
]

GENDER = [
    (0, "Male"),
    (1, "Female"),
]

class Bussel(models.Model):
    # Bussel Information ---------------------
    name            = models.CharField(max_length=50)
    code            = models.CharField(max_length=10)
    zone            = models.CharField(max_length=5)
    meeting_day     = models.IntegerField(choices=DAYS)
    meeting_time    = models.TimeField()
    password        = models.CharField(max_length=100) 

    # Bussel Location ------------------------
    house_number    = models.CharField(max_length=50)
    street_name     = models.CharField(max_length=50)
    suburb          = models.CharField(max_length=50)
    bussel_location = PointField(null=True)

    # Bussel Leader --------------------------
    leader = models.ForeignKey(Member)

    # Meta Data ------------------------------
    status       = models.IntegerField(choices=STATUS, default=0)
    date_created = models.DateField(auto_now_add=True)

    group_pic = models.URLField(null=True, blank=True, max_length=400)

    def __unicode__(self):
        return self.name + " (" + self.leader.first_name + " " + self.leader.last_name + ")"


# Weekly Report ------------------------------
class BusselReport(models.Model):
    bussel             = models.ForeignKey(Bussel)
    topic              = models.CharField(max_length=100)
    notes              = models.CharField(max_length=512, null=True)
    date               = models.DateField()
    time               = models.TimeField(auto_now_add=True)
    time_started       = models.TimeField()
    time_ended         = models.TimeField()
    bussel_attendance  = models.IntegerField()
    church_attendance  = models.IntegerField(default=0)
    num_souls_won      = models.IntegerField()
    num_first_timers   = models.IntegerField()
    offertory_given    = models.FloatField()

    class Meta:
        get_latest_by = 'date'

    def __unicode__(self):
        return self.bussel.name + "--" + self.topic

class Month(Func):
    function = 'EXTRACT'
    template = '%(function)s(MONTH from %(expressions)s)'
    output_field = models.IntegerField()

class BussellMember(models.Model):
    first_name = models.CharField(max_length=100)
    other_names = models.CharField(max_length=100)
    phone = models.CharField(max_length=15, null=True)
    address = models.CharField(max_length=100, null=True)
    date_of_birth = models.DateField()
    date_joined = models.DateField()
    gender = models.IntegerField(choices=GENDER, default=0)
    church_member = models.BooleanField(default=False)
    profile_pic = models.URLField(null=True, max_length=400)
    bussell = models.ForeignKey(Bussel)
    
    def __unicode__(self):
        return self.bussell.name + " -> " +self.first_name+ " "+self.other_names

class BussellMemberAttendance(models.Model):
    bussell_member = models.ForeignKey(BussellMember)
    bussell_report = models.ForeignKey(BusselReport)
    bussell_attendance = models.BooleanField(default=False)
    church_attendance = models.BooleanField(default=False)

    def __unicode__(self):
        return self.bussell_member.first_name + " " + str(self.bussell_attendance)

# Generate unique xxxx-xxxx hex code for each bussel
def get_hex_code():
    allowed_chars = 'ABCDEF0123456789'
    code = get_random_string(length=4, allowed_chars=allowed_chars) + \
        "-" + get_random_string(length=4, allowed_chars=allowed_chars)
    return code


# Signals --------------------------------------

# hash raw password from form
@receiver(pre_save, sender=Bussel)
def hash_password(sender, **kwargs):
    raw_password = kwargs['instance'].password
    if is_password_usable(raw_password):
        return
    else:
        hashed_password = make_password(raw_password)
        kwargs['instance'].password = hashed_password
    return


# get a unique hex code 
@receiver(pre_save, sender=Bussel)
def save_hex_code(sender, **kwargs):
    bussel = kwargs['instance']
    if bussel.pk is not None:
        print "already has code"
        return
    code = get_hex_code()
    existing_codes = Bussel.objects.all().values_list('code')
    while code in existing_codes:
        code = get_hex_code()
    bussel.code = code
    print code
    return

info_system/models.py
from django.db import models
from django.contrib.auth.models import User
from djgeojson.fields import PointField
import datetime

MARITAL_STATUS = [
(0, "Single"),
(1, "Married"),
(2, "Separated"),
(3, "Divorced"),
(4, "Widowed")
]

EDUCATION_LEVEL = [
(0, "None"),
(1, "Primary"),
(2, "Junior High School"),
(3, "Senior High School"),
(4, "First Degree"),
(5, "Second Degree"),
(6, "Doctorate Degree")
]

GENDER = [
(0, "Male"),
(1, "Female")
]

LANGUAGES = [
(0, "English"),
(1, "French"),
(2, "Akan"),
(3, "Ga"),
(4, "Ewe"),
(5, "Hausa"),
]

YES_NO = [
(0, "No"),
(1, "Yes")
]

MEMBERSHIP_STATUS= [
(0, "Inactive"),
(1, "Active")
]

ROLES = [
(0, "None"),
(1, "Pastor"),
(2, "Lady Pastor"),
(3, "Bussell Leader"),
(4, "Ministry Leader")
]

NATIONALITY = [
(0, "Ghanaian"),
(1, "Nigerian"),
(2, "Togolese"),
(3, "Beninois")
]

class Ministry(models.Model):
    name = models.CharField(max_length=50)
    purpose = models.CharField(max_length=500)

    def __unicode__(self):
        return self.name 

class Language(models.Model):
    name = models.CharField(max_length=20)

    def __unicode__(self):
        return self.name


class Member(models.Model):
    # personal info ----------------------------
    first_name     = models.CharField(max_length=20)
    middle_name    = models.CharField(max_length=20, blank=True, null=True)
    last_name      = models.CharField(max_length=20)
    gender         = models.IntegerField(choices=GENDER, default=0)
    phone          = models.CharField(max_length=15)
    marital_status = models.IntegerField(choices=MARITAL_STATUS, default=0)
    profile        = models.ImageField(upload_to="static/profiles/", blank=True, \
                                       default="static/profiles/default.png")
    date_of_birth  = models.DateField(default=datetime.date.today(), blank=True, null=True)
    place_of_birth = models.CharField(max_length=100, default="Accra", blank=True, null=True)
    nationality    = models.IntegerField(choices=NATIONALITY)
    nationality_at_birth = models.IntegerField(choices=NATIONALITY)
    hometown       = models.CharField(max_length=200, default="Madina, Greater Accra, Ghana", blank=True, null=True)
    tribal_origin  = models.CharField(max_length=200, default="Asante, Asante Region, Ghana", blank=True, null=True)
    email_address  = models.EmailField(null=True, blank=True)
    lingual_competency = models.ManyToManyField(Language)
    level_of_education = models.IntegerField(choices=EDUCATION_LEVEL, default=0)
    occupation = models.CharField(max_length=100, default="Unemployed", blank=True, null=True)

    # address ----------------------------------
    house_number = models.CharField(max_length=50, blank=True, null=True)
    street_name = models.CharField(max_length=50, blank=True, null=True)
    suburb      = models.CharField(max_length=50, blank=True, null=True)
    description_of_house = models.CharField(max_length=300, blank=True, null=True)
    member_location = PointField(null=True)

    # church info ------------------------------
    date_joined = models.DateField(default=datetime.date.today(), blank=True, null=True)
    baptized_by_immersion = models.IntegerField(choices=YES_NO, default=1)
    holy_ghost_baptism    = models.IntegerField(choices=YES_NO, default=0)
    leadership_role = models.IntegerField(choices=ROLES, default=0)
    ministries = models.ManyToManyField(Ministry, blank=True, null=True)
    membership_status = models.IntegerField(choices=MEMBERSHIP_STATUS, default=1)

    def __unicode__(self):
        return self.first_name + " " + self.middle_name + " " + self.last_name

class Manager(models.Model):
    user = models.OneToOneField(User)

class Shepherd(models.Model):
    user = models.OneToOneField(User)
    member = models.ForeignKey(Member)

    def __unicode__(self):
        return self.member.first_name + " "+ self.member.last_name + "--" + self.user.username

pastoral_care/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from info_system.models import Member
from django.core.exceptions import ValidationError


ATTENDANCE_TYPE = (
(0, "Sunday Morning Service"),
(1, "Wednesday Evening Service"),
(2, "Shepherds Meeting"),
(3, "Other")
)

class MasterAttendance(models.Model):
    description = models.CharField(max_length=2048)
    authorized_by = models.ForeignKey(Member)
    in_session = models.BooleanField(default=False)
    date_time = models.DateTimeField(auto_now=True)
    attendance_type = models.IntegerField(choices=ATTENDANCE_TYPE, default=0)
    head_count = models.IntegerField(default=0)
    first_timers = models.IntegerField(default=0)

class MemberAttendance(models.Model):
    master_attendance = models.ForeignKey(MasterAttendance)
    member = models.ForeignKey(Member)

class AttendanceOfficer(models.Model):
    shepherd_pk = models.IntegerField()
    status = models.BooleanField(default=False)
    assigned_members = ArrayField(models.IntegerField())

class AttendanceConfiguration(models.Model):
    attendance_in_session = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if AttendanceConfiguration.objects.exists() and not self.pk:
            raise ValidationError("Only one instance allowed here")
        else:
            return super(AttendanceConfiguration, self).save(*args, **kwargs)

def get_attendance_session_status():
    config = AttendanceConfiguration.objects.first()
    if config is None:
        config = AttendanceConfiguration()
        config.save()
    return config.attendance_in_session

def set_attendance_session_status(status):
    config = AttendanceConfiguration.objects.first()
    if config is None :
        config = AttendanceConfiguration()
    config.attendance_in_session = status
    config.save()

pastoral_care/forms.py
from django import forms
from info_system.models import GENDER, MARITAL_STATUS, NATIONALITY, YES_NO, ROLES, MEMBERSHIP_STATUS 
from info_system.models import EDUCATION_LEVEL, LANGUAGES
from info_system.models import Ministry, Language


class NewMemberForm(forms.Form):

    # personal info ----------------------------------------------
    first_name = forms.CharField(label='First Name', max_length=100,
                                 widget=forms.TextInput({"placeholder": "e.g Richard"}))

    middle_name = forms.CharField(label='Middle Name', max_length=100, required=False,
                                 widget=forms.TextInput({"placeholder": "e.g Ato"}))

    last_name = forms.CharField(label='Surname', max_length=100,
                                 widget=forms.TextInput({"placeholder": "e.g Mensah"}))

    phone = forms.CharField(label='Phone Number', max_length=100,
                                 widget=forms.TextInput({"placeholder": "e.g +233241234567"}))

    email_address = forms.EmailField(label="Email", max_length=50, required=False,
                                     widget=forms.EmailInput({"placeholder": "e.g example@gmail.com"}))

    gender = forms.ChoiceField(label="Gender",  choices=GENDER)

    marital_status = forms.ChoiceField(choices=MARITAL_STATUS)

    date_of_birth = forms.DateField(label="Date of Birth", required=False, widget=forms.TextInput({'placeholder': 'choose date'}))

    place_of_birth  = forms.CharField(label='Place of Birth', max_length=100, required=False,
                                 widget=forms.TextInput({"placeholder": "e.g Accra"}))

    hometown  = forms.CharField(label='Hometown (Town or City, Region or State or Province, Country)', max_length=200, required=False,
                                 widget=forms.TextInput({"placeholder": "e.g Chorkor, Greater Accra, Ghana"}))

    tribal_origin  = forms.CharField(label='Tribal Origin (Tribe, Region or State or Province, Country)', max_length=200, required=False,
                                 widget=forms.TextInput({"placeholder": "e.g Asante, Asante Region, Ghana"}))

    nationality_at_birth = forms.ChoiceField(choices=NATIONALITY)
    nationality  = forms.ChoiceField(choices=NATIONALITY)
    level_of_education = forms.ChoiceField(choices=EDUCATION_LEVEL)
    lingual_competency = forms.ModelMultipleChoiceField(Language.objects.all(), label="Lingual Comptence", required=False)
    occupation = forms.CharField(label="Current Occupation", max_length=100, required=False,
                                 widget=forms.TextInput({"placeholder":"e.g Police"}))

    # residence ------------------------------------------------------
    house_number  = forms.CharField(label='House Number', max_length=100, required=False,
                                 widget=forms.TextInput({"placeholder": "e.g B1043/15"}))

    street_name  = forms.CharField(label='Street Name', max_length=100, required=False,
                                 widget=forms.TextInput({"placeholder": "e.g Antruma St."}))

    suburb  = forms.CharField(label='Suburb', max_length=100, required=False,
                                 widget=forms.TextInput({"placeholder": "e.g Alafia"}))

    description_of_house  = forms.CharField(label='Description of Residence', max_length=1024, required=False,
                                 widget=forms.Textarea({"placeholder": "e.g. green storey building with blue gates adjacent to Azia Preparatory School"}))

    # church info ----------------------------------------------------
    date_joined = forms.DateField(label="Date Joined", required=False, widget=forms.TextInput({'placeholder': 'choose date'}))
    baptized_by_immersion  = forms.ChoiceField(label="Water Baptism By Immersion", choices=YES_NO)
    holy_ghost_baptism  = forms.ChoiceField(label="Holy Ghost Baptism", choices=YES_NO)
    leadership_role = forms.ChoiceField(label="Leadership Role", choices=ROLES)
    membership_status = forms.ChoiceField(label="Membership Status", choices=MEMBERSHIP_STATUS)
    ministries = forms.ModelMultipleChoiceField(Ministry.objects.all(), label="Ministries", required=False)

templates/pastoral_care/all_members.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}
{% block contents %}
<div class="main-contents">
    <div class="section-header">
	    <p class=section-title>All Members <span class="badge member-count">0</span></p>
	    <div class="section-item">
		    <a href="{% url 'pastoral:new-member'%}">
		     <span class="fa fa-plus"></span>
		     New
		 </a>
	    </div>
	    <input class=search-box id=member-search type="text" name="search" placeholder="Search...">
	    <input class=search-btn type="button" name="search-btn" value=Search>
	    

	    <div class="section-item">
	         <a href="#">
		     <span class="fa fa-sort"></span>
		     Sort
		 </a>
	    </div>

	    <div class="section-item dropdown">
	         <a href="#" data-toggle="dropdown" class="dropdown-toggle">
		     <span class="fa fa-upload"></span>
		     Export
		 </a>
		 <ul class="dropdown-menu">
			 <li><a href=""><span class="fa fa-file-excel-o"></span> Microsoft Excel</a></li>
			 <li><a href="{% url 'pastoral:export-members'%}?export_type=pdf"><span class="fa fa-file-pdf-o"></span> PDF Document</a></li>
		 </ul>
	    </div>
    </div>
    <div class="data-container">
	    <div class="empty_error_div">
		    <img src="/static/404_error_image.png" alt="not found" height:"205" width:"300" id="r404_image">
		   <h2 id="empty_error_string">Oops! Your request returned no data.</h2>
	    </div>

	<div class="row">

	</div>

    </div>
</div>
{% endblock %}
{% block footer %}
{% include "footer.html" %}
	<script>
$(document).ready(function(){
	$(".empty_error_div").hide();
	$("#pastoral_care_link").addClass("active");
	$("#members-all-link").addClass("active");
        $.ajax({
            type: 'GET',
            url: "{% url 'pastoral:all-members-json' %}",
	    dataType: 'json',
	    success: function(data) {
		    $.each(data, function(i, member) {
			    var link = "/pastoral/members/details/" + member.pk;
			    $(".data-container > .row").append('<div class="member-item col-xsm-12 col-md-4 col-lg-3"><div class="thumbnail"><a href='+link+ '><img class='+ "member-profile" +' src=/'+member.profile_url+'><p class=member-name>'+ member.first_name+ " "+ member.surname+ '</p> <div class="member-location"><span class="fa fa-map-marker"></span>&nbsp'+" " + member.suburb+'</div><div class="member-phone"><span class="fa fa-phone"></span>'+ " "+member.phone+'</a></div></div></div>'
					    )
		    })
		    $(".badge.member-count").html(data.length);
	    }
        })

	$(".search-box").keyup(function () {
	    var searchTerm = $(".search-box").val();
	    var listItem = $('.row').children('.member-item');
	    var searchSplit = searchTerm.replace(/ /g, "'):containsi('");
		        
		      $.extend($.expr[':'], {'containsi': function(elem, i, match, array){
		              return (elem.textContent || elem.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
		          }
		        });
	        
	      $("div.member-item").not(":containsi('" + searchSplit + "')").each(function(e){
	          $(this).hide();
		  if($("div.member-item").find(':visible').length===0){
		     console.log("all gone");
		     $(".empty_error_div").show(); 
		  }
	        });
	      
	        $("div.member-item:containsi('" + searchSplit + "')").each(function(e){
	            $(".empty_error_div").hide()
		    $(this).show();
		  })
        })
})
	</script>
{% endblock %}

templates/pastoral_care/member_detail.html
{% extends "base.html" %}

{% block contents %}
<div class="main-contents">
    <div class="section-header">
	    <p class="section-title">{{object.first_name}} {{object.middle_name}} {{object.last_name}}</p>
	    <div class=pull-right id=member-edit-link><a href="/pastoral/members/edit/{{object.pk}}/"><span class="fa fa-edit"></span> Edit</a></div>
    </div>
    <div class="data-container" id=bussel_details>
	    <div class="data-section bussel-general-info">
	           <div class="data-section-header">
			   <p class="subsection-title">Personal Information</p>
		   </div>
		   <div class="data-section-data">
			   <div class="row">
			       <div class="col-sm-4">
				       <p>First Name: <b>{{object.first_name}}</b></p>
			       </div>
			       <div class="col-sm-4">
				       <p>Middle Name: <b>{{object.middle_name}}</b></p>
			       </div>
			       <div class="col-sm-4">
				       <p>Surname: <b>{{object.last_name}}</b></p>
			       </div>
			   </div>
			   <div class="row">
			       <div class="col-sm-4">
				       <p>Phone Number: <b>{{object.phone}}</b></p>
			       </div>
			       <div class="col-sm-4">
				       <p>Email Address: <b>{{object.email_address}}</b></p>
			       </div>
			       <div class="col-sm-4">
				       <p>Gender:<a href="#"> <b>{{object.get_gender_display}}
				       </a></b></p>
			       </div>
			   </div>
			   <div class="row">
			       <div class="col-sm-4">
				       <p>Date of Birth: <b>{{object.date_of_birth}}</b></p>
			       </div>
			       <div class="col-sm-4">
				       <p>Place of Birth: <b>{{object.place_of_birth}}</b></p>
			       </div>
			       <div class="col-sm-4">
				       <p>Nationality at Birth:<a href="#"> <b>{{object.get_nationality_at_birth_display}}
				       </a></b></p>
			       </div>
			   </div>
			   <div class="row">
			       <div class="col-sm-4">
				       <p>Current Nationality: <b>{{object.get_nationality_display}}</b></p>
			       </div>
			       <div class="col-sm-4">
				       <p>Marital Status: <b>{{object.get_marital_status_display}}</b></p>
			       </div>
			       <div class="col-sm-4">
				       <p>Lingual Competence: <b>{{languages|join:', '}}</b></p>
			       </div>
			   </div>
		   </div>
	    </div>
	    <div class="data-section bussel-location-info">
	           <div class="data-section-header">
			   <p class="subsection-title">Residence Location Information</p>
		   </div>
		   <div class="data-section-data">
			   <div class="row">
			       <div class="col-sm-4">
				       <p>Suburb: <b>{{object.suburb}}</b> </p>
			       </div>
			       <div class="col-sm-4">
				       <p>Street: <b>{{object.street_name}}</b></p>
			       </div>
			       <div class="col-sm-4">
				       <p>House Number: <b>{{object.house_number}}</b></p>
			       </div>
			   </div>
			   <div class="map-view" id=member-location-map>
			   
			   </div>
		   </div>
	    </div>
	    <div class="data-section bussel-attendance-info">
	           <div class="data-section-header">
			   <p class="subsection-title">Membership Information</p>
		   </div>
		   <div class="data-section-data">
			   </div>
		   </div>
	    </div>
	    <div class="data-section bussel-offertory-info">
	           <div class="data-section-header">
			   <p class="subsection-title">Church Attendance Information</p>
		   </div>
		   <div class="data-section-data">
		   </div>
	    </div>
	    </div>
    </div>
</div>
{% endblock %}
{% block footer %}
{% include "footer.html" %}
	<script>
$(document).ready(function(){
	$("#pastoral_care_link").addClass("active");
	$("#members-all-link").addClass("active");
})
	</script>
{% endblock %}