bussels_app/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from django.views.generic import TemplateView
from views import *

urlpatterns = [
    url(r'^all/$', BusselListView.as_view(), name="all-bussels"),
    url(r'^authenticate/$', authenticate_bussel_request, name="bussel-authenticate"),
    url(r'^change/password/$', change_bussel_password, name="bussel-password-change"),
    url(r'^update/location/$', update_bussel_location, name="bussel-update-location"),
    url(r'^reports/all$', BusselReportListView.as_view(), name="all-bussel-reports"),
    url(r'^performance$', BussellPerformanceMetricsView.as_view(), name="bussel-performance"),
    url(r'^performance/json/$', get_performance_data, name="bussell-performance-json"),
    url(r'^performance/monthly_average/json/$', get_monthly_average, name="bussell-performance-monthly-json"),
    url(r'^reports/all/export$', export_bussels_list, name="all-bussel-export"),
    url(r'^reports/month/export$', export_bussel_monthly_reports, name="monthly-bussel-export"),
    url(r'^reports/headers/all/json/$', bussell_reports_header_json, name="all-bussel-header-list"),
    url(r'^reports/details/(?P<pk>\d+)/$', BusselReportEditView.as_view(), name="bussel-report-detail"),
    url(r'^all/json/$', json_bussel_list, name="all-bussels-json"),
    url(r'^reports/all/json$', json_bussel_reports_list, name="all-bussel-reports-json"),
    url(r'^reports_for_bussel/all/$', get_reports_for_bussel, name="reports-for-bussel"),
    url(r'^bussel_reports/all/export$', export_bussel_reports, name="bussel-reports-export"),
    url(r'^details/(?P<pk>\d+)/$', BusselDetailView.as_view(), name="bussel-detail"),
    url(r'^report/save/$', save_bussel_report, name="bussel-report-save"),
    url(r'^report/check/$', check_attendance_status, name="bussel-report-check"),
    url(r'^member/save/$', save_bussell_member, name="bussel-member-save"),
    url(r'^members/get/all/$', get_all_bussell_members, name="bussel-members-all"),
    url(r'^report/attendance/all/$', get_members_attendance_for_report, name="bussell-report-attendance"),
    url(r'^report/attendance/update/$', update_church_attendance),
    url(r'^profile/save/$', update_bussell_profile, name="bussel-profile-save"),
    url(r'^profile/get/$', get_bussell_group_pic_url, name="bussel-profile-get"),
]

lcidarkuman/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import bussels_app
import info_system

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    # Examples:
    # url(r'^$', 'lcidarkuman.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^bussels/', include('bussels_app.urls', namespace="bussel")),
    url(r'^info/', include('info_system.urls', namespace="info")),
    url(r'^pastoral/', include('pastoral_care.urls', namespace="pastoral")),
    url(r'^notice/', include('notice_board.urls', namespace="noticeboard")),
    url(r'^finance/', include('treasury.urls', namespace="finance")),
    url(r'^events/', include('events_calendar.urls', namespace="events")),
    url(r'^json/', include('bussels_app.urls', namespace="ajax")),
    url(r'^under_development/', bussels_app.views.SectionUnderDevelopment.as_view(), name="under-dev"),
    url(r'^$', bussels_app.views.SectionUnderDevelopment.as_view(), name="under-dev"),
    url(r'^access_denied/', bussels_app.views.AccessDenied.as_view(), name="access-denied"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('django.contrib.auth.urls')),
]

pastoral_care/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from views import *
from forms import *

urlpatterns = [
    url('^members/all/$', MemberShipListView.as_view(), name="all-members"),
    url('^members/details/(?P<pk>\d+)/$', MemberDetailView.as_view()),
    url('^members/edit/(?P<pk>\d+)/$', MemberEditView.as_view()),
    url('^members/all/json/$', json_member_list, name="all-members-json"),
    url('^members/new/$', AddNewMemberView.as_view(form_class=NewMemberForm), name="new-member"),
    url('^members/export$', export_members, name="export-members"),
    url('^attendance/authorize/$', authorize_attendance, name="authorize-attendance"),
    url('^attendance/start/$', start_attendance, name="start-attendance"),
    url('^attendance/finish/$', finish_attendance, name="finish-attendance"),
    url('^attendance/all/json/$', json_attendance_list, name="all-attendance-json"),
    url('^attendance/assigned/json/$', get_assigned_members, name="assigned-attendance-json"),
    url('^attendance/insession/details/$', get_attendance_insession_details, name="insession-details"),
    url('^attendance/submit/$', submit_attendance, name="attendance-submit"),
]

treasury/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from django.views.generic import TemplateView
from views import *

urlpatterns = [
    url(r'^offering/all/$', get_all_offerings, name="offering-all"),
    url(r'^tithe/all/$', get_all_tithes, name="tithe-all"),
    url(r'^tithe/add/$', add_tithe, name="tithe-add"),
    url(r'^offering/add/$', add_offering, name="offering-add"),
]

templates/.bussel_list.html
{% extends "base.html" %}

{% block contents %}
<h2>This is the bussel app page!</h2>
{% endblock %}

templates/base.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>LCI Darkuman</title>
      <link href="/static/css/bootstrap.min.css" rel="stylesheet">
      <link href="/static/css/custom.css" rel="stylesheet">
      <link href="/static/css/jquery-ui.min.css" rel="stylesheet">
      <link href="/static/css/formValidation.min.css" rel="stylesheet">
      <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet">
      <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
      <!--[if lt IE 9]>
	      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
              <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

	        <script src="/static/js/jquery.min.js"></script>
	    <!-- Include all compiled plugins (below), or include individual files as needed -->
	        <script src="/static/js/bootstrap.min.js"></script>
	        <script src="/static/js/jquery-ui.min.js"></script>
	        <script src="/static/js/formValidation.min.js"></script>
	        <script src="/static/js/framework/bootstrap.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@1.5.4/src/loadingoverlay.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@1.5.4/extras/loadingoverlay_progress/loadingoverlay_progress.min.js"></script>

		<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>

  </head>
          <body>
		  <div class="container">
			  {% block banner %}
			  <div class="banner">
			       <div class="logo">
			          <img src="/static/lci-logo.png" alt="logo" height="120" width="120">
			       </div>
			       
			       <div class="vertical-separator"></div>
			       <div class="brand-name">Lighthouse Chapel International</div>
	 		       <div class="brand-name-sub">Darkuman Branch</div>

			       {% if user.is_authenticated %}
		  <div class="user dropdown">
			  <a href="#" data-toggle="dropdown" class="dropdown-toggle" >
				  <span class="fa fa-user"> </span> {{user.username|lower}}
				  <span class="caret"></span> 
			  </a>
			  <ul class="dropdown-menu">
				  <li><a href="{% url 'password_change'%}"><span class="fa fa-lock"></span> Change Password</a></li>
				  <li><a href="{% url 'logout' %}?next=/login/"><span class="fa fa-arrow-right">
						  </span> Logout</a>
				  </li>
			  </ul>
		  </div>
		               {% endif %}

			  </div>
			  {% endblock %}

			  {% block navbar %}
			  <div class="navigation-bar">
			       <div class="nav-links-wrapper">
			            <ul class="nav-links">
					    <li class="nav-link"><a href="{%url 'under-dev'%}">Activities</a></li>
					    <li class="nav-link"><a href="{%url 'under-dev'%}">Finances</a></li>

					    <li class="nav-link dropdown">
				            <a href="#" class="dropbtn" id="pastoral_care_link">Pastoral Care</a>
					    <div class="dropdown-content">
						    <a href="{% url 'pastoral:all-members' %}" id=members-all-link>All Church Members</a>  
				                    <a href="#">Church Attendance</a>  
				                    <a href="#">Membership Statistics</a>  
					    </div>
					    </li>

					    <li class="nav-link dropdown">
                                            <a href="#" class="dropbtn" id=bussells_link>Bussells</a>
					    <div class="dropdown-content">
					            <a href="{%url 'bussel:all-bussels'%}" id=bussel-all-link>All Bussells</a>
						    <a href="{%url 'bussel:all-bussel-reports'%}"id=bussel-report-link>Weekly Reports</a>
						    <a href="{%url 'under-dev'%}">Bussell Statistics</a>
					    </div>
					    </li>
			            </ul>
			       </div>
			  </div>
			  {% endblock %}

			  {% block contents %}
			   <h1>This is the Base Template</h1>


			  {% endblock %}


			  {% block footer %}

			  {% endblock %}
		  </div>
	        <script src="/static/js/customjs.js"></script>
	  </body>
</html>

templates/base_out.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>LCI Darkuman</title>
      <link href="/static/css/bootstrap.min.css" rel="stylesheet">
      <link href="/static/css/custom.css" rel="stylesheet">
      <link href="/static/css/formValidation.min.css" rel="stylesheet">
      <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet">
      <!--[if lt IE 9]>
	      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
              <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

	        <script src="/static/js/jquery.min.js"></script>
	    <!-- Include all compiled plugins (below), or include individual files as needed -->
	        <script src="/static/js/bootstrap.min.js"></script>
	        <script src="/static/js/formValidation.min.js"></script>
	        <script src="/static/js/framework/bootstrap.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
  </head>
          <body>
		  <div class="container out">
			  {% block banner %}
			  <div class="banner out">
			       <div class="logo out">
			          <img src="/static/lci-logo.png" alt="logo" height="80" width="80">
			       </div>
			       
			       <div class="vertical-separator out"></div>
			       <div class="brand-name out">Lighthouse Chapel International</div>
			       <div class="brand-name-sub out">[Darkuman Branch]</div>

			  </div>
			  {% endblock %}

			  {% block contents %}
			   <h1>This is the Base Template</h1>


			  {% endblock %}


			  {% block footer %}

			  {% endblock %}
		  </div>
	        <script src="/static/js/customjs.js"></script>
		<style>
	            body {
		       background-color: white; 
		    }	
		</style>

	  </body>
</html>

templates/footer.html
<div id=footer>
	<div class="row footer-contents">
	
		<div class="col-sm-3 footer-chunk">
	             <div class="footer-header">
			     <span class="fa fa-heartbeat"></span>
                             Bussells
		     </div>
			     <ul class="footer-items">
				     <li><a href="#">Registered Bussells</a></li>
				     <li><a href="#">Latest Bussell Reports</a></li>
				     <li><a href="#">Inactive Bussells</a></li>
				     <li><a href="#">Search Reports</a></li>
				     <li><a href="#">Bussell Rankings</a></li>
			     </ul>
		</div>

		<div class="col-sm-3 footer-chunk">
	             <div class="footer-header">
			     <span class="fa fa-users"></span>
		          Pastoral Care 
		     </div>
			     <ul class="footer-items">
				     <li><a href="{% url 'pastoral:all-members'%}">All Church Members</a></li>
				     <li><a href="#">New Church Members</a></li>
				     <li><a href="#">Inactive Members</a></li>
				     <li><a href="#">Irregular Members</a></li>
				     <li><a href="#">Attendance Statistics</a></li>
			     </ul>
		</div>

		<div class="col-sm-3 footer-chunk">
	             <div class="footer-header">
			     <span class="fa fa-money"></span>
		          Finances
		     </div>
			     <ul class="footer-items">
				     <li><a href="#">Non-Tithing Members</a></li>
				     <li><a href="#">Expenses</a></li>
				     <li><a href="#">Financial Statistics</a></li>
			     </ul>
		</div>

		<div class="col-sm-3 footer-chunk">
	             <div class="footer-header">
			     <span class="fa fa-tachometer"></span>
		          Activities
		     </div>
			     <ul class="footer-items">
				     <li><a href="#">This Week</a></li>
				     <li><a href="#">Upcoming Events</a></li>
				     <li><a href="#">Past Events</a></li>
				     <li><a href="#">Cancelled Events</a></li>
			     </ul>
		</div>
	</div>
</div>